name: flasop
description: application de ecommerce qui permet de faire presque le tour des widgets flutter. Très intéressant meme s&#x27;il y a quelque complication à partir de la connexion à firebase.Mais comme toute appli, ce n&#x27;est jamais aussi simple quand on apprend.Bonne chance

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9
  google_sign_in: ^4.0.6
  shared_preferences: ^0.5.3+4
  fluttertoast: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/a1.jpeg
    - images/a2.jpeg
    - images/a3.jpeg
    - images/a4.jpeg
    - images/a5.jpeg

    - images/logo.png
    - images/logo/logo.png

    - images/c1.jpg
    - images/m1.jpeg
    - images/m2.jpg
    - images/w1.jpeg
    - images/w3.jpeg
    - images/w4.jpeg

    - images/tshirt.png
    - images/dress.png
    - images/formal.png
    - images/informal.png
    - images/shoe.png
    - images/jeans.png
    - images/accessories.png

    - images/products/blazer1.jpeg
    - images/products/blazer2.jpeg
    - images/products/dress1.jpeg
    - images/products/dress2.jpeg
    - images/products/hills1.jpeg
    - images/products/hills2.jpeg
    - images/products/pants1.jpg
    - images/products/pants2.jpeg
    - images/products/shoe1.jpg
    - images/products/skt1.jpeg
    - images/products/skt2.jpeg

  fonts:
    - family: Avenir
      fonts:
        - asset: linux/fonts/Avenir/AvenirNextLTPro-Bold.otf
        - asset: linux/fonts/Avenir/AvenirNextLTPro-Regular.otf
        - asset: linux/fonts/Avenir/AvenirNextLTPro-Italic.otf
    - family: Exo2
      fonts:
        - asset: linux/fonts/exo-2/Exo2-Black.otf
        - asset: linux/fonts/exo-2/Exo2-BlackItalic.otf
        - asset: linux/fonts/exo-2/Exo2-Bold.otf
        - asset: linux/fonts/exo-2/Exo2-BoldItalic.otf
        - asset: linux/fonts/exo-2/Exo2-ExtraBold.otf
        - asset: linux/fonts/exo-2/Exo2-ExtraBoldItalic.otf
        - asset: linux/fonts/exo-2/Exo2-Italic.otf
        - asset: linux/fonts/exo-2/Exo2-Light.otf
        - asset: linux/fonts/exo-2/Exo2-Medium.otf
        - asset: linux/fonts/exo-2/Exo2-Regular.otf
        - asset: linux/fonts/exo-2/Exo2-Thin.otf
    - family: Curve
      fonts:
        - asset: linux/fonts/learning_curve/True/curve_bold.ttf
        - asset: linux/fonts/learning_curve/True/curve_regular.ttf
    - family: Roboto
      fonts:
        - asset: linux/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: linux/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: linux/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: linux/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: linux/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: linux/fonts/Roboto/Roboto-Black.ttf
          weight: 900